# Generated by Django 3.1.3 on 2021-03-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='num',
        ),
    ]
