# Generated by Django 3.1.7 on 2021-03-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_lottery_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='num',
            field=models.CharField(default='', max_length=6),
        ),
    ]
