# Generated by Django 3.1.7 on 2021-03-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210317_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='num',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
